# Generated by Django 2.2.14 on 2021-12-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='quiz_type',
            field=models.CharField(choices=[('s', 'Sequential'), ('p', 'Progression')], max_length=10, null=True),
        ),
    ]
