# Generated by Django 2.2.14 on 2021-12-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userquiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='difficulty',
            field=models.CharField(choices=[('g', 'Green'), ('b', 'Blue'), ('r', 'Red')], default='b', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='quiz_type',
            field=models.CharField(choices=[('s', 'Sequential'), ('p', 'Progression')], max_length=20, null=True),
        ),
    ]
