# Generated by Django 2.2.14 on 2021-12-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_userquiz_bg_transparency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='bold',
            field=models.BooleanField(choices=[(True, 'Y'), (False, 'N')], default=False),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='fileshare_path',
            field=models.CharField(default='https://', max_length=100),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='font_color',
            field=models.CharField(default='White', max_length=20),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='font_name',
            field=models.CharField(choices=[('1', 'Arial'), ('2', 'Helvetica'), ('3', 'Calibri'), ('4', 'Futura'), ('5', 'Garamond'), ('6', 'Times New Roman'), ('7', 'Cambria'), ('8', 'Verdana'), ('9', 'Rockwell'), ('10', 'Franklin Gothic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='font_size',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='retention_period',
            field=models.IntegerField(blank=True, default=270, null=True),
        ),
    ]
