# Generated by Django 2.2.14 on 2021-12-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20211225_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='font_name',
            field=models.CharField(choices=[('1', 'Arial'), ('2', 'Helvetica'), ('3', 'Calibri'), ('4', 'Futura'), ('5', 'Garamond'), ('6', 'Times New Roman'), ('7', 'Cambria'), ('8', 'Verdana'), ('9', 'Rockwell'), ('10', 'Franklin Gothic')], default='1', max_length=20, null=True),
        ),
    ]
