# Generated by Django 2.2.14 on 2021-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20211225_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquiz',
            old_name='fileshare_path',
            new_name='file_share_path',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='bg_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquiz',
            name='bg_image_type',
            field=models.CharField(blank=True, choices=[('s', 'Solid'), ('i', 'Image')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='solid_color',
            field=models.CharField(default='Blue', max_length=50),
        ),
    ]
