# Generated by Django 2.2.14 on 2021-12-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20211225_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='bg_image',
            field=models.ImageField(blank=True, default='https://www.w3schools.com/images/picture.jpg', null=True, upload_to=''),
        ),
    ]
