# Generated by Django 2.2.14 on 2022-01-10 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20211225_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='no_of_artifact',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
