# Generated by Django 2.2.14 on 2022-01-11 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20220110_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='local_folder',
            field=models.CharField(default='/media', max_length=100),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='tag_line_font_size',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='tag_line_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='bg_image_type',
            field=models.CharField(choices=[('s', 'Solid'), ('i', 'Image')], default='s', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='bg_transparency',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='quiz_type',
            field=models.CharField(choices=[('s', 'Sequential'), ('p', 'Progression')], default='s', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='solid_color',
            field=models.CharField(blank=True, default='Blue', max_length=50, null=True),
        ),
    ]
