# Generated by Django 2.2.14 on 2022-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20220111_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='insrtctions',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
