# Generated by Django 3.2.11 on 2022-01-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_userquiz_file_share_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='logo_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
